version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      cluster.name: "playground"
      node.name: "Docker_1"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      path.repo: "['/var/tmp/es_backups']"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    ports:
      - 5601:5601
    # made explicit, but by default configured within the kibana container config
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601']

networks:
  esnet:
    driver: bridge